[build-system]
build-backend = "poetry.core.masonry.api"
requires = [
  "poetry-core>=1.5",
]

[tool.poetry]
name = "tap-db2"
version = "1.0.5"
description = "Singer tap for db2"
license = "Apache-2.0"
authors = ["Mark Johnston <mj2.squ@gmail.com>"]
maintainers = ["Mark Johnston <mj2.squ@gmail.com>"]
readme = "README.md"
repository = "https://github.com/mjsqu/tap-db2"
keywords = ["singer.io", "elt", "db2"]

[tool.poetry.dependencies]
python = "<3.12,>=3.7.1"
attrs = "22.2.0"
ibm-db-sa = "0.3.8"
ibm-db = "3.1.4"
jinja2 = "3.1.2"
markupsafe = "<2.2.0"
pendulum = "2.1.2"
pyodbc = "4.0.35"
pytz = ">=2018.1"
singer-python = ">=5.12.0"
sqlalchemy = "<2.0.0"

[tool.poetry.scripts]
tap-db2 = 'tap_db2:main'