# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: DB2 Image

on:
  push:
    branches: [ "main", "feature/github_actions" ]
    #paths:
    #  - "tap_db2/*"


jobs:
  build:

    runs-on: ubuntu-latest
    services:
      ibm_db2:
        image: "icr.io/db2_community/db2"
        env:
          LICENSE: accept
          DB2INSTANCE: db2inst1
          DB2INST1_PASSWORD: password
          DBNAME: testdb
        options: "--privileged=true"
        ports:
          - "50000:50000"

    steps:
    - name: "Perform healthcheck from the outside"
      run: "docker logs -f ${{ job.services.ibm_db2.id }} | sed '/(*) Setup has completed./ q'"
