name: Test Tap

on:
 workflow_dispatch:


jobs:
  build:
  
    runs-on: ubuntu-latest
    steps:
    
    - name: "Perform healthcheck from the outside"
      run: >- 
        docker logs -f ${{ job.services.ibm_db2.id }} | 
        sed '/(*) Setup has completed./ q'
    - name: Get DB2 Database State
      run: >-
        docker exec ${{ job.services.ibm_db2.id }} 
        su - db2inst1 -c 'db2 get connection state'
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
        architecture: x64

    - name: Install Poetry
      run: |
        pipx install poetry
        poetry --version

    - name: Install dependencies
      run: |
        poetry install
    - name: Run Tap
      run: |
        poetry run tap-db2 --config tests/db2_config.json --discover
    
    
    services:
      ibm_db2:
        image: "icr.io/db2_community/db2"
        env:
          LICENSE: accept
          DB2INSTANCE: db2inst1
          DB2INST1_PASSWORD: password
          DBNAME: testdb
        options: >-
          --privileged=true
        ports:
          - 50000:50000
